//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_DoAn.dtb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khach_Hang
    {
        public string MA_KH { get; set; }
        public string HO_TEN_KH { get; set; }
        public string SDT_KH { get; set; }
        public string DIA_CHI { get; set; }
        public string EMAIL { get; set; }
        public string ANH_DAI_DIEN { get; set; }
        public string ID_User { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
