//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_DoAn.dtb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phuong_Thuc_Thanh_Toan
    {
        public int ID_THANH_TOAN { get; set; }
        public string TEN_PHUONG_THUC { get; set; }
    }
}
