//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_DoAn.dtb
{
    using System;
    using System.Collections.Generic;
    
    public partial class San_Pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public San_Pham()
        {
            this.Hinh_Anh_San_Pham = new HashSet<Hinh_Anh_San_Pham>();
        }
    
        public string MA_SP { get; set; }
        public string TEN_SP { get; set; }
        public string MO_TA { get; set; }
        public string HINH_ANH { get; set; }
        public decimal GIA_GOC { get; set; }
        public Nullable<int> DISCOUNT { get; set; }
        public Nullable<decimal> GIA_BAN { get; set; }
        public int TON_KHO { get; set; }
        public int ID_TRANG_THAI { get; set; }
        public int ID_DANH_MUC { get; set; }
        public string MA_KHUYEN_MAI { get; set; }
        public int ID_TAC_GIA { get; set; }
        public int ID_NXB { get; set; }
        public int ID_The_Loai { get; set; }
    
        public virtual Danh_Muc Danh_Muc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hinh_Anh_San_Pham> Hinh_Anh_San_Pham { get; set; }
        public virtual Khuyen_Mai Khuyen_Mai { get; set; }
        public virtual Nha_Xuat_Ban Nha_Xuat_Ban { get; set; }
        public virtual Tac_Gia Tac_Gia { get; set; }
        public virtual The_Loai The_Loai { get; set; }
        public virtual Trang_Thai Trang_Thai { get; set; }
    }
}
